### ISSUE TITLE
compile error when dev 

### ISSUE THREAD

**Issue by Benleie** [nuxt/koa#52]
After installation,when `npm run dev`：
Error: Plugin/Preset files are not allowed to export objects, only functions.
![image](https://user-images.githubusercontent.com/24362871/47257106-15d4ae00-d4bc-11e8-86fb-e05ffe789e72.png)

And i updated backpack-core to 0.7.0, but this error still exists.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/koa-template/issues/c35">#c35</a>)</em></sub></div>

**Comment by Benleie** [comment]
so i have to use nuxt@1.4.x to fix it

**Comment by you06** [comment]
Issue occurs due to:
* no `babel-loader`(node.js itself does not support es6 `import`)
* outdated dependencies

My solution:
install `babel-loader`, upgrade `eslint-loader`
```sh
yarn remove eslint-loader
yarn add -D eslint-loader babel-loader
```
edit `backpack.config.js`
```js
module.exports = {
  webpack: (config, options, webpack) => {
    config.entry.main = './server/index.js'
    config.module = {
      rules: [
        {
          test: /\.js$/,
          loader: "babel-loader",
          exclude: /(node_modules)/
        }
      ]
    }
    return config
  }
}
```

I've open a pull request fix this issue, just try `vue init you06/koa-template <project-name>` before merge accepted.
